name: Build

on:
  push:
    branches: [master]
  # pull_request:
  #   branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [v1.x.x]
        node-version: [16.x]

    env:
      DENO_DIR: deno-cache-dir


    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn
          cache-dependency-path: ./frontend/yarn.lock

      - name: Install frontend dependencies
        working-directory: ./frontend
        run: yarn

      - name: Build frontend
        working-directory: ./frontend
        run: yarn build

      - name: Use Deno ${{ matrix.deno-version }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ matrix.deno-version }}

      - name: Cache server dependencies 
        uses: actions/cache@v3
        with:
          key: ${{ hashFiles('**/deno.lock') }}
          path: ${{ env.DENO_DIR }}

      - name: Build server
        working-directory: ./server
        run: deno task build
